// Minimal zero-dependency static server for hosting HTML previews.
//
// Railway's default static serving injects a restrictive Content-Security-Policy
// that blocks the blob:/data: URLs and new Function() eval that Claude Code
// "bundled page" exports rely on, so previews render blank. This server serves
// the same files with a CSP that permits exactly what those bundles need, while
// still blocking plugins/framing of untrusted origins.

import { createServer } from "node:http";
import { createReadStream, readFileSync, existsSync } from "node:fs";
import { stat, mkdir, readFile, writeFile, rename } from "node:fs/promises";
import { join, normalize, extname } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash, timingSafeEqual, randomUUID } from "node:crypto";

const ROOT = fileURLToPath(new URL(".", import.meta.url)).replace(/\/+$/, "");
const PORT = process.env.PORT || 3000;

// Clean-URL slug map, generated by scripts/build-index.mjs. Each entry maps a
// slug to its project's primary page and base folder, so previews are served at
// /<slug>/ (and their assets at /<slug>/<path>) instead of raw folder paths.
let SLUGS = new Map();
try {
  const manifest = JSON.parse(readFileSync(join(ROOT, "previews.json"), "utf8"));
  SLUGS = new Map(manifest.map((p) => [p.slug, p]));
} catch {
  /* no manifest yet — slug routing off, static serving still works */
}

// Optional Glaze logo for the preview banner. Drop a file at brand/glaze-logo.svg
// (or .png) and it is used automatically; otherwise a text wordmark is shown.
const LOGO_SRC = ["brand/glaze-logo.svg", "brand/glaze-logo.png"].find((p) =>
  existsSync(join(ROOT, p))
);
const YEAR = new Date().getFullYear();

function escapeHtml(s) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

// URL for a project's raw primary file (each path segment encoded).
function rawUrl(primary) {
  return "/" + primary.split("/").map(encodeURIComponent).join("/");
}

// A thin wrapper served at /<slug>/ : a fixed confidential banner above the
// preview (loaded in a frame), plus a slide-out comments sidebar. The banner
// and sidebar sit outside the frame, so the preview's own runtime re-render
// cannot remove them.
function bannerWrapper(project, isTeam) {
  const logo = LOGO_SRC
    ? `<img class="gz-logo" src="/${LOGO_SRC.split("/").map(encodeURIComponent).join("/")}" alt="Glaze Digital" />`
    : `<span class="gz-word">Glaze</span>`;
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${escapeHtml(project.title)} — Glaze Digital</title>
<style>
  html, body { margin: 0; height: 100%; background: #0f1115; }
  .gz-bar {
    position: fixed; top: 0; left: 0; right: 0; height: 40px;
    display: flex; align-items: center; justify-content: space-between;
    padding: 0 16px; box-sizing: border-box;
    background: #0f1115; border-bottom: 1px solid #262b36;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    z-index: 2147483647; box-shadow: 0 1px 8px rgba(0,0,0,.4);
  }
  .gz-left { display: flex; align-items: center; gap: 12px; min-width: 0; }
  .gz-right { display: flex; align-items: center; gap: 14px; min-width: 0; }
  .gz-logo { height: 20px; width: auto; display: block; }
  .gz-word { font-size: 15px; font-weight: 700; letter-spacing: .16em; text-transform: uppercase; color: #6ea8fe; }
  .gz-title { color: #9aa3b2; font-size: 13px; font-weight: 500; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
  .gz-note { color: #9aa3b2; font-size: 12px; font-weight: 400; letter-spacing: .01em; white-space: nowrap; }
  .gz-cbtn { appearance: none; border: 1px solid #2b3240; background: #171a21; color: #e7eaf0;
    font: 600 12px/1 inherit; padding: 7px 12px; border-radius: 8px; cursor: pointer; white-space: nowrap; }
  .gz-cbtn:hover { border-color: #34506e; }
  .gz-cbtn .n { color: #6ea8fe; }
  .gz-frame { position: fixed; top: 40px; left: 0; width: 100%; height: calc(100% - 40px); border: 0; background: #fff; transition: width .16s ease; }
  body.gz-open .gz-frame { width: calc(100% - 340px); }
  .gz-comments { position: fixed; top: 40px; right: 0; bottom: 0; width: 340px; transform: translateX(100%);
    transition: transform .16s ease; background: #12151b; border-left: 1px solid #262b36;
    z-index: 2147483646; display: flex; flex-direction: column;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; color: #e7eaf0; }
  body.gz-open .gz-comments { transform: translateX(0); }
  .gz-ch { padding: 13px 16px; border-bottom: 1px solid #262b36; display: flex; align-items: center; justify-content: space-between; }
  .gz-ch b { font-size: 13px; font-weight: 600; }
  .gz-x { appearance: none; background: none; border: 0; color: #9aa3b2; font-size: 18px; line-height: 1; cursor: pointer; }
  .gz-list { flex: 1; overflow: auto; padding: 10px 14px; display: flex; flex-direction: column; gap: 10px; }
  .gz-item { background: #171a21; border: 1px solid #232834; border-radius: 10px; padding: 10px 12px; }
  .gz-item.res { opacity: .5; }
  .gz-m { display: flex; justify-content: space-between; gap: 8px; font-size: 11px; color: #9aa3b2; margin-bottom: 4px; }
  .gz-nm { font-weight: 600; color: #c7ccd6; }
  .gz-bd { font-size: 13px; line-height: 1.45; white-space: pre-wrap; word-break: break-word; }
  .gz-ac { display: flex; gap: 12px; margin-top: 8px; }
  .gz-ac button { appearance: none; background: none; border: 0; color: #6ea8fe; font: 600 11px/1 inherit; cursor: pointer; padding: 0; }
  .gz-empty { color: #6b7280; font-size: 13px; text-align: center; padding: 26px 10px; }
  .gz-form { border-top: 1px solid #262b36; padding: 12px 14px; display: flex; flex-direction: column; gap: 8px; }
  .gz-form input, .gz-form textarea { width: 100%; box-sizing: border-box; background: #0f1115; border: 1px solid #262b36;
    border-radius: 8px; color: #e7eaf0; font: 13px/1.4 inherit; padding: 8px 10px; outline: none; }
  .gz-form textarea { resize: vertical; min-height: 62px; }
  .gz-form input:focus, .gz-form textarea:focus { border-color: #6ea8fe; }
  .gz-send { background: #6ea8fe; color: #0f1115; border: 0; font-weight: 700; padding: 9px; border-radius: 8px; cursor: pointer; }
  .gz-send:hover { background: #8bbcff; }
  @media (max-width: 640px) {
    .gz-title, .gz-note { display: none; }
    .gz-comments { width: 100%; }
    body.gz-open .gz-frame { width: 100%; visibility: hidden; }
  }
</style>
</head>
<body>
  <div class="gz-bar">
    <div class="gz-left">
      ${logo}
      <span class="gz-title">${escapeHtml(project.title)}</span>
    </div>
    <div class="gz-right">
      <button class="gz-cbtn" id="gz-toggle" aria-label="Toggle comments">Comments <span class="n" id="gz-count"></span></button>
      <div class="gz-note">© ${YEAR} Glaze Digital — confidential; not for distribution or reproduction.</div>
    </div>
  </div>
  <iframe class="gz-frame" src="${escapeHtml(rawUrl(project.primary))}"></iframe>
  <aside class="gz-comments" aria-label="Comments">
    <div class="gz-ch"><b>Comments</b><button class="gz-x" id="gz-close" aria-label="Close">×</button></div>
    <div class="gz-list" id="gz-list"></div>
    <form class="gz-form" id="gz-form">
      <input id="gz-name" type="text" placeholder="Your name" maxlength="80" autocomplete="name" />
      <textarea id="gz-text" placeholder="Leave a comment on this design…" maxlength="4000"></textarea>
      <button class="gz-send" type="submit">Post comment</button>
    </form>
  </aside>
  <script>
  (function () {
    var SLUG = ${JSON.stringify(project.slug)}, TEAM = ${isTeam ? "true" : "false"};
    var body = document.body;
    var list = document.getElementById("gz-list");
    var countEl = document.getElementById("gz-count");
    var nameIn = document.getElementById("gz-name");
    function esc(s){ var d=document.createElement("div"); d.textContent=(s==null?"":String(s)); return d.innerHTML; }
    function fmt(iso){ try { return new Date(iso).toLocaleString(undefined,{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"}); } catch(e){ return ""; } }
    function render(items){
      countEl.textContent = items.length ? String(items.length) : "";
      if(!items.length){ list.innerHTML = '<div class="gz-empty">No comments yet.<br>Add the first note below.</div>'; return; }
      list.innerHTML = items.map(function(c){
        return '<div class="gz-item'+(c.resolved?" res":"")+'" data-id="'+esc(c.id)+'">'
          + '<div class="gz-m"><span class="gz-nm">'+esc(c.name)+'</span><span>'+fmt(c.created)+'</span></div>'
          + '<div class="gz-bd">'+esc(c.body)+'</div>'
          + '<div class="gz-ac"><button data-act="resolve">'+(c.resolved?"Unresolve":"Resolve")+'</button>'
          + (TEAM?'<button data-act="delete">Delete</button>':'')
          + '</div></div>';
      }).join("");
    }
    function load(){
      fetch("/api/comments?slug="+encodeURIComponent(SLUG)).then(function(r){return r.json();})
        .then(function(d){ render((d&&d.comments)||[]); }).catch(function(){});
    }
    function toggle(open){ body.classList.toggle("gz-open", open); if(open) load(); }
    document.getElementById("gz-toggle").addEventListener("click", function(){ toggle(!body.classList.contains("gz-open")); });
    document.getElementById("gz-close").addEventListener("click", function(){ toggle(false); });
    try { nameIn.value = localStorage.getItem("gz_name") || ""; } catch(e){}
    document.getElementById("gz-form").addEventListener("submit", function(e){
      e.preventDefault();
      var name = nameIn.value.trim(), text = document.getElementById("gz-text").value.trim();
      if(!text) return;
      try { localStorage.setItem("gz_name", name); } catch(e){}
      fetch("/api/comments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({slug:SLUG,name:name,body:text})})
        .then(function(r){return r.json();}).then(function(){ document.getElementById("gz-text").value=""; load(); }).catch(function(){});
    });
    list.addEventListener("click", function(e){
      var btn = e.target.closest ? e.target.closest("button") : null; if(!btn) return;
      var item = e.target.closest(".gz-item"); if(!item) return;
      var id = item.getAttribute("data-id"), act = btn.getAttribute("data-act");
      if(act==="resolve"){
        fetch("/api/comments/resolve",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:id,resolved:!item.classList.contains("res")})}).then(load);
      } else if(act==="delete"){
        if(!confirm("Delete this comment?")) return;
        fetch("/api/comments/delete",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:id})}).then(load);
      }
    });
    // Load the count on first paint so the button shows how many comments exist.
    load();
  })();
  </script>
</body>
</html>
`;
}

// Password gate for the gallery index. Set PREVIEW_PASSWORD on Railway to keep
// the password out of this (public) repo; falls back to a default so it works
// without configuration.
const PASSWORD = process.env.PREVIEW_PASSWORD || "glaze26";
const COOKIE_NAME = "gp_auth";
// Deterministic session token derived from the password — the cookie never
// contains the password itself, and a new password invalidates old cookies.
const AUTH_TOKEN = createHash("sha256")
  .update(PASSWORD + "::glaze-previews-v1")
  .digest("hex");
// Only the gallery is gated; individual preview files stay reachable by their
// (intentionally shared) direct links.
const GATED_PATHS = new Set(["/index.html"]);

function parseCookies(header) {
  const out = {};
  if (!header) return out;
  for (const part of header.split(";")) {
    const i = part.indexOf("=");
    if (i === -1) continue;
    out[part.slice(0, i).trim()] = decodeURIComponent(part.slice(i + 1).trim());
  }
  return out;
}

function isAuthed(req) {
  const token = parseCookies(req.headers.cookie)[COOKIE_NAME];
  if (!token || token.length !== AUTH_TOKEN.length) return false;
  try {
    return timingSafeEqual(Buffer.from(token), Buffer.from(AUTH_TOKEN));
  } catch {
    return false;
  }
}

function readBody(req, limit = 4096) {
  return new Promise((resolve) => {
    let data = "";
    req.on("data", (c) => {
      data += c;
      if (data.length > limit) req.destroy();
    });
    req.on("end", () => resolve(data));
    req.on("error", () => resolve(""));
  });
}

function loginPage(error) {
  const msg = error
    ? `<p class="err">Incorrect password. Try again.</p>`
    : "";
  return `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Glaze Digital — Client Previews</title>
<style>
  *{box-sizing:border-box}
  body{margin:0;min-height:100vh;display:flex;align-items:center;justify-content:center;
    background:#0f1115;color:#e7eaf0;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif}
  .card{width:100%;max-width:340px;padding:36px 30px;background:#171a21;border:1px solid #262b36;border-radius:14px;text-align:center}
  .brand{font-size:12px;letter-spacing:.14em;text-transform:uppercase;color:#6ea8fe;font-weight:600;margin:0 0 6px}
  h1{font-size:20px;margin:0 0 22px;font-weight:600}
  input{width:100%;padding:11px 13px;font-size:15px;color:#e7eaf0;background:#0f1115;
    border:1px solid #262b36;border-radius:9px;margin-bottom:12px;outline:none}
  input:focus{border-color:#6ea8fe}
  button{width:100%;padding:11px;font-size:15px;font-weight:600;color:#0f1115;background:#6ea8fe;
    border:none;border-radius:9px;cursor:pointer}
  button:hover{background:#8bbcff}
  .err{color:#ff8a80;font-size:13px;margin:0 0 12px}
</style></head>
<body>
  <form class="card" method="POST" action="/__auth">
    <p class="brand">Glaze Digital</p>
    <h1>Client Previews</h1>
    ${msg}
    <input type="password" name="password" placeholder="Password" autofocus autocomplete="current-password" required>
    <button type="submit">View previews</button>
  </form>
</body></html>`;
}

// CSP validated against the bundled-page format: scripts need 'unsafe-eval'
// (the runtime uses new Function()) plus blob:/data:; fonts/images/media/styles
// are delivered as blob: URLs unpacked at runtime.
const CSP = [
  "default-src 'self'",
  "img-src 'self' data: blob: https: *",
  "style-src 'self' 'unsafe-inline' data: blob: https: *",
  "script-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob: https: *",
  "font-src 'self' data: blob: https: *",
  "connect-src 'self' data: blob: https: *",
  "media-src 'self' data: blob: https: *",
  "object-src 'none'",
  "frame-src 'self' https: *",
].join("; ");

const TYPES = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".webp": "image/webp",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".txt": "text/plain; charset=utf-8",
  ".pdf": "application/pdf",
  ".mp4": "video/mp4",
  ".webm": "video/webm",
};

function send(res, status, body, headers = {}) {
  res.writeHead(status, {
    "Content-Security-Policy": CSP,
    "X-Content-Type-Options": "nosniff",
    "Referrer-Policy": "strict-origin-when-cross-origin",
    ...headers,
  });
  res.end(body);
}

// ---- comments store --------------------------------------------------------
// Durable JSON store. Railway sets RAILWAY_VOLUME_MOUNT_PATH automatically when
// a volume is attached — point a volume there and comments persist across
// deploys. Without a volume it falls back to ./data (works, but ephemeral).
const DATA_DIR =
  process.env.DATA_DIR || process.env.RAILWAY_VOLUME_MOUNT_PATH || join(ROOT, "data");
const COMMENTS_FILE = join(DATA_DIR, "comments.json");
const SLACK_WEBHOOK = process.env.SLACK_WEBHOOK_URL || "";
const MAX_NAME = 80;
const MAX_BODY = 4000;

async function loadComments() {
  try {
    const data = JSON.parse(await readFile(COMMENTS_FILE, "utf8"));
    return Array.isArray(data.comments) ? data.comments : [];
  } catch {
    return [];
  }
}

// Serialize read-modify-write so concurrent posts can't clobber the file.
let writeChain = Promise.resolve();
function withComments(mutator) {
  const run = writeChain.then(async () => {
    const comments = await loadComments();
    const result = await mutator(comments);
    await mkdir(DATA_DIR, { recursive: true });
    const tmp = COMMENTS_FILE + ".tmp";
    await writeFile(tmp, JSON.stringify({ comments }, null, 2), "utf8");
    await rename(tmp, COMMENTS_FILE);
    return result;
  });
  writeChain = run.catch(() => {});
  return run;
}

function clean(s, max) {
  return String(s == null ? "" : s).slice(0, max).trim();
}

function sendJson(res, status, obj) {
  send(res, status, JSON.stringify(obj), {
    "Content-Type": "application/json; charset=utf-8",
  });
}

async function notifySlack(c, title) {
  if (!SLACK_WEBHOOK) return;
  try {
    await fetch(SLACK_WEBHOOK, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        text: `:speech_balloon: New comment on *${title}* by ${c.name}:\n> ${c.body}`,
      }),
    });
  } catch {
    /* best-effort */
  }
}

const server = createServer(async (req, res) => {
  try {
    // Decode and strip query/hash, default "/" to the gallery index.
    let pathname = decodeURIComponent((req.url || "/").split("?")[0].split("#")[0]);

    // Login form submission for the gallery gate.
    if (req.method === "POST" && pathname === "/__auth") {
      const body = await readBody(req);
      const params = new URLSearchParams(body);
      const ok =
        (params.get("password") || "") === PASSWORD && PASSWORD.length > 0;
      if (ok) {
        const secure =
          (req.headers["x-forwarded-proto"] || "").split(",")[0].trim() ===
          "https";
        return send(res, 303, null, {
          Location: "/",
          "Set-Cookie": `${COOKIE_NAME}=${AUTH_TOKEN}; HttpOnly; SameSite=Lax; Path=/; Max-Age=2592000${secure ? "; Secure" : ""}`,
        });
      }
      return send(res, 401, loginPage(true), {
        "Content-Type": "text/html; charset=utf-8",
      });
    }

    // ---- Comments API ----
    // Previews are shared by link, so listing / adding / resolving are open;
    // deleting is restricted to the logged-in team (gallery password cookie).
    if (pathname === "/api/comments") {
      if (req.method === "GET") {
        const slug = new URL(req.url, "http://x").searchParams.get("slug") || "";
        const all = await loadComments();
        return sendJson(res, 200, { comments: all.filter((c) => c.slug === slug) });
      }
      if (req.method === "POST") {
        const raw = await readBody(req, MAX_BODY + MAX_NAME + 2000);
        let p;
        try { p = JSON.parse(raw || "{}"); } catch { p = {}; }
        const slug = clean(p.slug, 200);
        const name = clean(p.name, MAX_NAME) || "Anonymous";
        const text = clean(p.body, MAX_BODY);
        if (!slug || !SLUGS.has(slug) || !text) {
          return sendJson(res, 400, { error: "Missing slug or comment." });
        }
        const comment = {
          id: randomUUID(),
          slug,
          name,
          body: text,
          created: new Date().toISOString(),
          resolved: false,
        };
        await withComments((list) => list.push(comment));
        notifySlack(comment, (SLUGS.get(slug) || {}).title || slug);
        return sendJson(res, 200, { comment });
      }
      return sendJson(res, 405, { error: "Method not allowed." });
    }
    if (pathname === "/api/comments/resolve" && req.method === "POST") {
      const raw = await readBody(req);
      let p;
      try { p = JSON.parse(raw || "{}"); } catch { p = {}; }
      const ok = await withComments((list) => {
        const c = list.find((x) => x.id === p.id);
        if (!c) return false;
        c.resolved = !!p.resolved;
        return true;
      });
      return sendJson(res, ok ? 200 : 404, { ok });
    }
    if (pathname === "/api/comments/delete" && req.method === "POST") {
      if (!isAuthed(req)) return sendJson(res, 403, { error: "Not allowed." });
      const raw = await readBody(req);
      let p;
      try { p = JSON.parse(raw || "{}"); } catch { p = {}; }
      const ok = await withComments((list) => {
        const i = list.findIndex((x) => x.id === p.id);
        if (i === -1) return false;
        list.splice(i, 1);
        return true;
      });
      return sendJson(res, ok ? 200 : 404, { ok });
    }

    if (pathname === "/" || pathname === "") pathname = "/index.html";

    // Gate the gallery: serve the login form unless the visitor is authed.
    if (GATED_PATHS.has(pathname) && !isAuthed(req)) {
      if (req.method === "HEAD") {
        return send(res, 401, null, { "Content-Type": "text/html; charset=utf-8" });
      }
      return send(res, 401, loginPage(false), {
        "Content-Type": "text/html; charset=utf-8",
      });
    }

    // Clean-URL slug routing: /<slug>/ -> the project's primary page,
    // /<slug>/<asset> -> a file inside the project's folder. Previews are not
    // gated (they are shared by direct link).
    const segs = pathname.split("/").filter(Boolean);
    if (segs.length && SLUGS.has(segs[0])) {
      const project = SLUGS.get(segs[0]);
      if (segs.length === 1) {
        // Redirect /<slug> -> /<slug>/ for a stable base URL.
        if (!pathname.endsWith("/")) {
          return send(res, 301, null, { Location: `/${project.slug}/` });
        }
        // Serve the banner wrapper (the preview loads in its frame).
        return send(res, 200, bannerWrapper(project, isAuthed(req)), {
          "Content-Type": "text/html; charset=utf-8",
        });
      }
      const rest = segs.slice(1).join("/");
      const target = project.base ? join(project.base, rest) : rest;
      return serveFile(req, res, join(ROOT, target));
    }

    // Fallback: serve the raw path (keeps older direct links working).
    return serveFile(req, res, join(ROOT, pathname));
  } catch (err) {
    console.error("Request error:", err);
    send(res, 500, "Internal server error", { "Content-Type": "text/plain" });
  }
});

// Stream a file from disk with the shared security headers, or 403/404.
async function serveFile(req, res, requested) {
  const filePath = normalize(requested);
  if (filePath !== ROOT && !filePath.startsWith(ROOT + "/")) {
    return send(res, 403, "Forbidden", { "Content-Type": "text/plain" });
  }

  let info;
  try {
    info = await stat(filePath);
  } catch {
    return send(res, 404, "Not found", { "Content-Type": "text/plain" });
  }
  if (info.isDirectory()) {
    return send(res, 404, "Not found", { "Content-Type": "text/plain" });
  }

  const type = TYPES[extname(filePath).toLowerCase()] || "application/octet-stream";
  const headers = {
    "Content-Security-Policy": CSP,
    "X-Content-Type-Options": "nosniff",
    "Referrer-Policy": "strict-origin-when-cross-origin",
    "Content-Type": type,
    "Content-Length": info.size,
    "Last-Modified": info.mtime.toUTCString(),
    "Cache-Control": "public, max-age=300",
  };

  if (req.method === "HEAD") {
    res.writeHead(200, headers);
    return res.end();
  }
  res.writeHead(200, headers);
  createReadStream(filePath).pipe(res);
}

server.listen(PORT, "0.0.0.0", () => {
  console.log(`Glaze Previews server listening on :${PORT}`);
});
